### ISSUE TITLE
建议增加合并 ignore 文件的功能

### ISSUE THREAD

**Issue by sanheng** [guoyunhe/init-roll#1]
init-roll 里面对这些文件进行合并删除处理
![image](https://github.com/guoyunhe/init-roll/assets/13793256/e08c28c1-25c3-4f50-89b0-868b3a419b45)

在实际使用的情况下发现 ingore 文件应该是合并而不是直接删除，因为每个项目可能有自己的 ignore 规则。
比如下面这个是本项目的 ignore 文件内容，在使用这个工具时会被直接删掉以下 ignore 内容
![image](https://github.com/guoyunhe/init-roll/assets/13793256/81838206-c819-4da2-a82e-31bd9416700c)

**Comment by guoyunhe** [comment]
目前没有工具能够实现可靠的 ignore 规则合并，ignore 规则是有先后顺序的，合并导致顺序改变会产生不可预知的结果，因此目前并不支持这种用法。用户需要自行通过 git diff 来调整生成结果
